// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: web/protobuf/gateway/user.proto

package pb_gateway

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	base "go-web/web/protobuf/base"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bases *base.Base `protobuf:"bytes,1,opt,name=bases,proto3" json:"bases,omitempty"`
	ID    int32      `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_protobuf_gateway_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_web_protobuf_gateway_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_web_protobuf_gateway_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetBases() *base.Base {
	if x != nil {
		return x.Bases
	}
	return nil
}

func (x *User) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_web_protobuf_gateway_user_proto protoreflect.FileDescriptor

var file_web_protobuf_gateway_user_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x77, 0x65, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x70, 0x62, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x1a, 0x23, 0x67,
	0x6f, 0x2d, 0x77, 0x65, 0x62, 0x2f, 0x77, 0x65, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x05, 0x62, 0x61,
	0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x05, 0x62, 0x61, 0x73, 0x65, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x32,
	0x33, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x44, 0x65,
	0x6d, 0x6f, 0x33, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x6f, 0x2d, 0x77, 0x65, 0x62, 0x2f, 0x77,
	0x65, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x3b, 0x70, 0x62, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_web_protobuf_gateway_user_proto_rawDescOnce sync.Once
	file_web_protobuf_gateway_user_proto_rawDescData = file_web_protobuf_gateway_user_proto_rawDesc
)

func file_web_protobuf_gateway_user_proto_rawDescGZIP() []byte {
	file_web_protobuf_gateway_user_proto_rawDescOnce.Do(func() {
		file_web_protobuf_gateway_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_web_protobuf_gateway_user_proto_rawDescData)
	})
	return file_web_protobuf_gateway_user_proto_rawDescData
}

var file_web_protobuf_gateway_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_web_protobuf_gateway_user_proto_goTypes = []interface{}{
	(*User)(nil),      // 0: pb_gateway.User
	(*base.Base)(nil), // 1: pb_base.Base
}
var file_web_protobuf_gateway_user_proto_depIdxs = []int32{
	1, // 0: pb_gateway.User.bases:type_name -> pb_base.Base
	1, // 1: pb_gateway.Service.Demo3:input_type -> pb_base.Base
	0, // 2: pb_gateway.Service.Demo3:output_type -> pb_gateway.User
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_web_protobuf_gateway_user_proto_init() }
func file_web_protobuf_gateway_user_proto_init() {
	if File_web_protobuf_gateway_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_web_protobuf_gateway_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web_protobuf_gateway_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_protobuf_gateway_user_proto_goTypes,
		DependencyIndexes: file_web_protobuf_gateway_user_proto_depIdxs,
		MessageInfos:      file_web_protobuf_gateway_user_proto_msgTypes,
	}.Build()
	File_web_protobuf_gateway_user_proto = out.File
	file_web_protobuf_gateway_user_proto_rawDesc = nil
	file_web_protobuf_gateway_user_proto_goTypes = nil
	file_web_protobuf_gateway_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Demo3(ctx context.Context, in *base.Base, opts ...grpc.CallOption) (*User, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Demo3(ctx context.Context, in *base.Base, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb_gateway.Service/Demo3", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Demo3(context.Context, *base.Base) (*User, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Demo3(context.Context, *base.Base) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Demo3 not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Demo3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(base.Base)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Demo3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_gateway.Service/Demo3",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Demo3(ctx, req.(*base.Base))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb_gateway.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Demo3",
			Handler:    _Service_Demo3_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web/protobuf/gateway/user.proto",
}
